module.exports = Object.freeze({
  SUBMIT_REQUEST: 'SUBMIT_REQUEST',
  SUBMIT_SUCCESS: 'SUBMIT_SUCCESS',
  SUBMIT_FAILURE: 'SUBMIT_FAILURE',
  RESET_ALERT: 'RESET_ALERT',
  RETRIEVE_REQUEST: 'RETRIEVE_REQUEST',
  RETRIEVE_SUCCESS: 'RETRIEVE_SUCCESS',
  RETRIEVE_FAILURE: 'RETRIEVE_FAILURE'
})
